from .inline import (
    main_menu_keyboard,
    cabinet_keyboard,
    tariffs_keyboard,
    gift_tariffs_keyboard,
    gift_payment_method_keyboard,
    support_keyboard,
    payment_method_keyboard,
    subscription_actions_keyboard,
    language_keyboard,
    back_keyboard,
    admin_inline_keyboard,
    admin_promos_keyboard,
    admin_promo_view_keyboard,
    admin_promo_type_keyboard,
    admin_promo_plan_keyboard,
    confirm_cancel_keyboard,
    about_keyboard,
    reset_key_keyboard,
)
from .reply import admin_reply_keyboard, remove_keyboard

__all__ = [
    "main_menu_keyboard",
    "cabinet_keyboard",
    "tariffs_keyboard",
    "gift_tariffs_keyboard",
    "gift_payment_method_keyboard",
    "support_keyboard",
    "payment_method_keyboard",
    "subscription_actions_keyboard",
    "language_keyboard",
    "back_keyboard",
    "admin_inline_keyboard",
    "admin_promos_keyboard",
    "admin_promo_view_keyboard",
    "admin_promo_type_keyboard",
    "admin_promo_plan_keyboard",
    "confirm_cancel_keyboard",
    "about_keyboard",
    "reset_key_keyboard",
    "admin_reply_keyboard",
    "remove_keyboard",
]
